services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: ["start-dev"]

  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: 123456

