application:
  name: es_krake_server
  version: 0.0.1

logger:
  level: DEBUG
  format: JSON

server:
  port: 8080

rdb:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  name: ek_t1
  max_open_conns: 10
  max_idle_conns: 3
  max_life_time: 100000000
  max_idle_time: 100000
  # migrations_path: migrations
