services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    restart: on-failure:3
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"

volumes:
  minio-data:
