services:
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure:3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ../../scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo.sh:ro
      - mongo-data:/data/db
      - mongo-data-config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure:3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mdb

volumes:
  mongo-data:
    name: mongo-data
  mongo-data-config:
    name: mongo-data-config

networks:
  mdb:
    driver: bridge
