services:
  esk-rdb:
    image: postgres:17-alpine3.21
    container_name: esk-rdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "krake", "-d", "esk_dev_1"]
    environment:
      POSTGRES_DB: esk_dev_1
      POSTGRES_USER: krake
      POSTGRES_PASSWORD: 123456
      MIGRATOR_INITIAL_PASSWORD: 123456
      EXPORTER_USER: postgres_exporter
      EXPORTER_PASSWORD: pgex
    ports:
      - 5432:5432
    volumes:
      - esk-rdb-data:/var/lib/postgresql/data
      - ../../scripts/esk-rdb-initdb.sh:/docker-entrypoint-initdb.d/esk_rdb.sh
    networks:
        - esk-rdb

volumes:
  esk-rdb-data:
    name: esk-rdb-data

networks:
  esk-rdb:
    driver: bridge
    name: esk-rdb
