services:
  redis:
    image: redis
    container_name: redis
    restart: on-failure:3
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    name: redis-data
