services:
  vault-dev:
    image: hashicorp/vault:latest
    container_name: vault-dev
    restart: on-failure:3
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_SKIP_VERIFY=true
      - VAULT_ADDR=https://127.0.0.1:8200
      - ESK_RDB_MASTER_USERNAME=krake
      - ESK_RDB_MASTER_PASSWORD=123456
      - ESK_RDB_CONN_URL=postgres://krake:123456@esk-rdb:5432/krake?sslmode=disable
      - ESK_RDB_NAME=esk_dev_1
    volumes:
      - vault-data:/vault
      - ./policies:/vault/policies
      - ../../scripts/init-vault-dev.sh:/entrypoint.sh
    networks:
        - esk-rdb
    cap_add:
      - IPC_LOCK
    entrypoint: ["/entrypoint.sh"]

volumes:
  vault-data: 
    name: vault-data

networks:
  esk-rdb:
    external: true
