services:
  vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    restart: on-failure:3
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_SKIP_VERIFY=true
    cap_add:
      - IPC_LOCK
    entrypoint: ["vault", "server", "-dev", "-dev-root-token-id", "root", "-dev-tls"]
