services:
  vault-dev:
    image: hashicorp/vault:latest
    container_name: vault-dev
    restart: on-failure:3
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_SKIP_VERIFY=true
      - VAULT_ADDR=https://127.0.0.1:8200
      - ESK_RDB_MASTER_USERNAME=krake
      - ESK_RDB_MASTER_PASSWORD=123456
      - ESK_RDB_NAME=esk_dev_1
      - REDIS_APP_USER=esk
      - REDIS_APP_PASSWORD=esk123
      - REDIS_ADMIN_USER=admin
      - REDIS_ADMIN_PASSWORD=admin123
      - ESK_MDB_NAME=esk_mdb_dev_1
      - ESK_MDB_MASTER_USERNAME=esk_admin
      - ESK_MDB_MASTER_PASSWORD=esk_admin123456
      - ESK_ESDB_USERNAME=esk_vault
      - ESK_ESDB_PASSWORD=esk_vault123456
      - ESK_ESDB_URL=http://es-db:9200
    volumes:
      - vault-data:/vault
      - ./policies:/vault/policies
      - ../../scripts/vault-dev-entrypoint.sh:/entrypoint.sh
    networks:
        - esk-rdb
        - esk-mdb
        - elastic
    cap_add:
      - IPC_LOCK
    entrypoint: ["/entrypoint.sh"]

volumes:
  vault-data :
    name: vault-data

networks:
  esk-rdb:
    external: true
  esk-mdb:
    external: true
  elastic:
    external: true
