global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'esk-rdb'
    static_configs:
      - targets: ['rdb-exporter:9187']
